title: HDM App Docs
description: Documentation for the Hierarchical Decision Modeling web application
theme: just-the-docs

url: https://yourusername.github.io
baseurl: /hdm-docs

# Enable features
search_enabled: true
heading_anchors: true

# Navigation
nav_enabled: true

aux_links:
  GitHub Repository: https://github.com/yourusername/hdm-docs
